export const siteConfig = {
  name: 'href.lol',
  description: 'Create your beautiful bio page with href.lol - The #1 Bio Link Tool for creators, influencers, and professionals. Free, modern, and easy to use.',
  url: 'https://href.lol',
  ogImage: 'https://href.lol/og.jpg',
  links: {
    twitter: 'https://twitter.com/hrefdotlol',
    github: 'https://github.com/hrefdotlol',
  },
  creator: 'href.lol',
  keywords: [
    'bio',
    'bio tool',
    'bio link',
    'bio page',
    'bio links',
    'bio profile',
    'bio website',
    'bio creator',
    'bio maker',
    'bio generator',
    'bio page maker',
    'bio page creator',
    'bio page generator',
    'bio link tool',
    'bio link maker',
    'bio link creator',
    'bio link generator',
    'ezbio',
    'ezbiotool',
    'ez bio',
    'ez bio tool',
    'link in bio',
    'links in bio',
    'bio links page',
    'bio profile page',
    'bio website maker',
    'bio website creator',
    'bio website generator',
    'social media bio',
    'social media links',
    'social media profile',
    'social media page',
    'social media bio page',
    'social media bio maker',
    'social media bio creator',
    'social media bio generator',
    'instagram bio',
    'instagram bio link',
    'instagram bio page',
    'instagram bio maker',
    'instagram bio creator',
    'instagram bio generator',
    'tiktok bio',
    'tiktok bio link',
    'tiktok bio page',
    'tiktok bio maker',
    'tiktok bio creator',
    'tiktok bio generator',
    'twitter bio',
    'twitter bio link',
    'twitter bio page',
    'twitter bio maker',
    'twitter bio creator',
    'twitter bio generator',
    'youtube bio',
    'youtube bio link',
    'youtube bio page',
    'youtube bio maker',
    'youtube bio creator',
    'youtube bio generator',
    'free bio tool',
    'free bio maker',
    'free bio creator',
    'free bio generator',
    'free bio page maker',
    'free bio page creator',
    'free bio page generator',
    'free bio link tool',
    'free bio link maker',
    'free bio link creator',
    'free bio link generator',
  ],
  authors: [{ name: 'href.lol' }],
  defaultLocale: 'en_US',
  social: {
    twitter: '@hrefdotlol',
  },
  nav: {
    main: [
      { title: 'Home', href: '/' },
      { title: 'Features', href: '/#features' },
      { title: 'Pricing', href: '/pricing' },
      { title: 'Showcase', href: '/showcase' },
    ],
    footer: {
      quickLinks: [
        { title: 'Home', href: '/' },
        { title: 'Features', href: '/#features' },
        { title: 'Pricing', href: '/pricing' },
        { title: 'Showcase', href: '/showcase' },
      ],
      resources: [
        { title: 'Blog', href: '/blog' },
        { title: 'Documentation', href: '/docs' },
        { title: 'API', href: '/api' },
        { title: 'Support', href: '/support' },
      ],
      information: [
        { title: 'Terms of Service', href: '/terms' },
        { title: 'Platform Guidelines', href: '/guidelines' },
        { title: 'Privacy Policy', href: '/privacy' },
        { title: 'FAQ', href: '/faq' },
      ],
    },
  },
} as const;

export type SiteConfig = typeof siteConfig; 